TXT = {"green_general":
        {
            "title": "Uwagi dotyczące MW.11, MW.12, MW.14, MW.15 i MW.16",
            "content": '''{Ponownie przedstawiono do dyskusji tylko niewielkie zmiany w projekcie planu, ale nie można zapomnieć o setkach uwag zgłoszonych przez osoby mieszkające w okolicy.;Projekt przedstawiony do ponownej dyskusji nadal opiera się na założeniu, że niewolnicze trzymanie się studium uwarunkowań jest ważniejsze od głosu mieszkańców, czy też ustaleń wynikających z takich dokumentów, jak prognoza oddziaływania na środowisko.;Zmiany objęte ponownym wyłożeniem nie są wystarczające i nie odpowiadają na liczne wcześniejsze uwagi mieszkańców.;Plan poddany ponownemu wyłożeniu nie odpowiada wystarczająco na liczne wcześniejsze uwagi.;Projektowany plan, mimo niewielkich zmian, nadal niesłusznie przeznacza niemal cały niezabudowany dotąd teren pod inwestycje.;Nowa wersja projektu wprowadza tylko niewielkie zmiany. Twórcy projektu wciąż przewidują, że większość niezabudowanego jeszcze terenu ma być poddana intensywnej zabudowie mieszkaniowej i usługowej.;W stosunku do pierwotnego projektu wprowadzono bardzo nieliczne zmiany, które nie odpowiadają na uwagi mieszkańców. Nie można zapomnieć, że uwagi te były oparte na dokumentach sporządzonych przez sam Urząd Miasta (zwłaszcza prognozie oddziaływania na środowisko).} 
            {Szkoda, że projekt po zmianach nadal ma te same wady, co pierwotny - zakłada zabudowanie terenów cennych przyrodniczo i ważnych dla zapobiegania podtopieniom (przed czym przestrzegano w prognozie oddziaływania na środowisko).;Ponownie wyłożony projekt nadal przewiduje, że na cele inwestycyjne zostaną przeznaczone obszary cenne przyrodniczo (nie tylko "na papierze", ale także w rzeczywistości).;Nowy projekt nadal przewiduje zabudowę na obszarach cennych przyrodniczo i ważnych dla retencji wody opadowej.;Zaktualizowana prognoza oddziaływania na środowisko nadal wskazuje, że wdrożenie takiego planu wpłynie szkodliwie na cenne siedliska i ograniczy retencyjne walory terenu.;Twórcy prognozy oddziaływania na środowisko ostrzegają, że zabudowa terenu negatywnie wpłynie na tereny otaczające obszar opracowania, w szczególności obszar Lasu Borkowskiego.;Jak wynika nawet z poddanej aktualizacji prognozy oddziaływania na środowisko, przeznaczenie niezabudowanej części terenu pod inwestycje wpłynie niekorzytnie na przyrodę oraz zakłóci stosunki wodne, grożąc częstszymi podtopieniami.} 
            {Zdecydowanie opowiadam się za przeznaczeniem terenów oznaczonych teraz jako MW.11, MW.12, MW.14, MW.15 i MW.16 pod zieleń urządzoną.;Moim zdaniem niezabudowane jeszcze tereny w południowej części obszaru powinny być przeznaczone pod zieleń urządzoną (np. park).;Proszę, aby tereny MW.11, MW.12, MW.14, NW.15 i MW.16 w całości przeznaczyć na zieleń urządzoną (ZP, np. park).;Uważam, że cenne przyrodniczo tereny w południowej części obszaru należy zakwalifikować w planie jako zieleń, zamiast budować na nich kolejne osiedla.;Tereny od MW.11 do MW.16 powinno się przeznaczyć na zieleń urządzoną (ZP). Dzięki temu miasto mogłoby w przyszłości wykupić je i urządzić, z korzyścią dla mieszkańców.;Przypominam, że studium uwarunkowań pozwala przeznaczyć pod zieleń tereny, które generalnie oznaczono jako MW (zabudowa wielorodzinna). Takie powinno być przeznaczenie terenów określanych obecnie jako MW.11, MW.12, MW.14, MW.15 i MW.16.;Tereny MW.11, MW.12, MW.14, MW.15 i MW.16 należy przeznaczyć pod zieleń urządzoną.;Tereny MW.11, MW.12, MW.14, MW.15 i MW.16 nie powinny być obszarami inwestycyjnymi - mamy ich już dość w okolicy. Powinny pozostać zielone, a by miasto mogło je wykupić z rąk prywatnych, powinny być przeznaczone w planie pod zieleń urządzoną.}'''
        },
        "green_roofs":
        {
            "title": "Uwagi dotyczące MW.8, MW.11, MW.12, MW/U.6",
            "content": '''{Zakładając, że wbrew sprzeciwowi mieszkańców cenne zielone tereny zostaną zabudowane, należy łagodzić negatywne skutki takiej decyzji. Dlatego uważam, że należy rozszerzyć obowiązek stosowania dachu zielonego intensywnego.;Dachy zielone intensywne w mojej ocenie trzeba obecnie stosować nie tylko na garażach, ale także na budynkach mieszkalnych. Taki obowiązek już wprowadzono dla terenów MW.14, MW.15 i MW.16.;Uważam, że stosowanie dachów zielonych intensywnych powinno być obowiązkow dla wszystkich terenów, które teraz są niezabudowane, a miasto dąży (wbrew głosom mieszkańców) do ich zabudowania.;Nie powinno się ograniczać obowiązku stoowania dachów zielonych intensywnych tylko do garaży podziemnych.} 
            {Jeśli takie dachy zostaną zastosowane także na budynkach mieszkalnych, pozwoli to choć trochę wyrównać straty wynikające z oddania terenu pod inwestycje.;Powinno się w jak największym stopniu zabezpieczyć możliwość retencjonowania wody - najlepiej zadziałałoby tu przeznaczenie terenu pod zieleń, ale jeśli miasto nie wysłucha tu mieszkańców, powinno i tak dążyć do zachowania retencji.;Skoro obowiązek  używania zielonych dachów intensywnych wprowadzono już dla niektórych obszarów, ten sam wymóg powinien być stosowany także na innych terenach inwestycyjnych.;Zastosowanie intensywnych dachów zielonych, choć nie da takich korzyści, jak utrzymanie obecnej zieleni, przynajmniej w części będzie dawać korzyści związane z retencjonowaniem opadów.} 
            { ;Zdecydowanie uważam, że dachy zielone intensywne należy stosować na budynkach mieszkalnych także na obszarach MW.8, MW.11, MW.12, MW/U.6.;Wnioskuję o poszerzenie obowiązku stosowania zielonych dachów intensywnych na budynkach mieszkalnych o obszary MW.8, MW.11, MW.12, MW/U.6.;Proszę rozszerzyć obowiązek stosowania zielonych dachów intensywnych na budynkach mieszkalnych i objąć nim także obszary MW.8, MW.11, MW.12, MW/U.6.}
            '''
        },
        "green_mw11":
        {
            "title": "Uwagi dotyczące MW.11",
            "content": '''{Co prawda w nowej wersji projektu pojawił się pas zieleni między terenami MW.11 i MW.9, ale jest on bardzo wąski. Teren MW.11 jako osiedle nadal bez uzasadnienia dzieliłby dwa cenne przyrodniczo tereny zielone (oznaczone jako ZPw.4 i ZPz.4).;Strefa zieleni osiedlowej wprowadzona wzdłuż zachodniej granicy MW.11 nie jest wystarczająco duża.;Strefa zieleni osiedlowej między MW.11 a MW.9 jest zdecydowanie zbyt mała.;Strefa zieleni osiedlowej w zachodniej części obszaru MW.11 powinna być większa. W obecny projekcie teren przeznaczony pod zabudowę oddziela dwa cenne tereny zielone, które mają zostać zachowane (tj. ZPw.4 i ZPz.4).}            
            {Mieszkańcy dotąd konsekwentnie sprzeciwiali się przeznaczeniu całego terenu MW.11 pod inwestycje. Jeśli mimo to zostanie on terenem inwestycyjnym, pas zieleni osiedlowej należy poszerzyć. Powinien sięgać przynajmniej od granicy z MW.9 aż do terenu zielonego ZPz.4.;Moim zdaniem należy zachować w jak największym zakresie walory przyrodnicze tego terenu i jego zdolność do retencji wody (już teraz jest to przecież teren podmokły). Jeżeli zostanie przeznaczony pod zabudowę, powinno się ją ograniczyć w ten sposób, że zielone tereny ZPz.4, ZPw.4, nowy pas zieleni osiedlowej i obszar znajdujący się pomiędzy nimi zostaną połączone w jeden obszar zieleni urządzonej ZP.;Moim zdaniem fragment pomiędzy  ZPz.4 a ZPw.4 i MW.9 powinien być przenaczony pod zieleń urządzoną.} 
            {Sądzę też, że nie powinno się budować na terenie MW.11 garaży podziemnych, ponieważ głęboka zabudowa grozi utratą zdolności do retencjonowania wody.;Jeśli miasto chce zabdować ten teren, mimo jego cennych walorów retencyjnych, powinno przynajmniej zakazać zabudowy głębokiej (garaży podziemnych), która te walory praktycznie zlikwiduje.;Oprócz tego, jeśli miasto wbrew głosom mieszkańów przeznaczy ten teren pod zabududowę, należy ograniczyć intensywność zabudowy. Można to osiągnąć zwiększając wskaźnik terenu biologicznie czynnego do 60%, zmniejszając wskaźnik powierzchni zabudowy na 25% i ustalając wskaźnik intensywności zabudowy na 0,1-1,0.;Niezależnie od powyższego, jeśli obszar MW.11 miałby zostać przeznaczony pod zabudowę, maksymalną wysokość zabudowy należy zmniejszyć do 11 metrów (trzech kondygnacji). Należy też ograniczyć długość elewacji, podobnie jak dla MW.12. Pozwoli to zachować spójność z sąsiadującą zabudową jednorodzinną.}

            '''
        },
        "green_mw12":
        {
            "title": "Uwagi dotyczące MW.12",
            "content": '''{Myślę, że nawet jeśli teren zostanie przeznaczony pod zabudowę, miasto i tak powinno pamiętać o tym, żeby ograniczyć presję na środowisko.;Gdyby ten teren miał zostać zabudowany, choć obecnie jest cenny przyrodniczo i przydatny dla retencji wody, trzeba ograniczyć straty w  tych obszarach. Trzeba też pamiętać o zachowaniu spójności z sąsiednimi domami jednorodzinnymi.;Zakładając, że wbrew uwagom mieszkańców opartym na prognozie oddziaływania na środowisko, teren MW.12 ma stać się terenem inwestycyjnym, nie powinna być to intensywna zabudowa. Trzeba ograniczyć jej wysokość i zachować jak najwięcej retencyjnych walorów terenu.} 
            {Uważam, że należy zakazać na obszarze MW.12 budowy garaży podziemnych, które spowodowałyby utratę jego walorów retencyjnych, a także ograniczyć maksymalną wysokość zabudowy.;Stosowanie garaży podziemnych, z uwagi na związane z tym odwodnienie terenu, nie powinno być dozwolone. Wysokość budynków mieszkalnych powinna być mniejsza, dostosowana do wysokości sąsiadujących domów jednorodzinnych.;Dlatego wnioskuję o zwiększenie wskaźnika terenu biologicznie czynnego do 60%, ustalenie maksymalnego wskaźnika powierzchni zabudowy na 25% i wskaźnika intensywności zabudowy na 0,1-1,0.;Zabudowa powinna mieć maksymalnie ok. 11 metrów (trzy kondygnacje), tak żeby domy wielorodzinne nie górowały nad sąsiadującymi domkami.}

            '''
        },
        "green_mw14":
        {
            "title": "Uwagi dotyczące MW.14 i okolicznych terenów",
            "content": '''{W prezentacji dla mieszkańców wskazano, że sąsiadujący z MW.14 obszar ZPw.5 został poszerzony. Ale to poszerznie jest minimalne, w dodatku odbyło się kosztem zmniejszenia innego skrawka zieleni.;W nowym projekcie trochę poszerzono teren ZPw.5, ale jednocześnie zmniejszono ZPw.7. Efekt jest taki, że łączna powierzchnia zieleni w okolicy jest nadal bardzo mała.;Nowy projekt planu ma tę samą wadę, co poprzedni - w okolicy MW.14 przewidziano za mało terenów zieleni osiedlowej, a nieliczne okoliczne tereny zieleni urządzonej są bardzo małe.}            
            {Cały teren MW.14 powinien pozostać zielony, tak jak wcześniej apelowali o to mieszkańcy i tak, jak wynika z rekomendacji zawartych w takich dokumentach, jak prognoza oddziaływania na środowisko. Jeśli mimo to ma być terenem inwestycyjnym, trzeba przynajmniej poszerzyć strefy zieleni osiedlowej.;Uważam, że powinno się rozszerzyć strefy ochrony zieleni osiedlowej (przy założeniu, że miasto nie zdecyduje się pozostawić tu zieleni, tak jak postulują to mieszkańcy i eksperci samego urzędu).;Jeśli wnioski o przeznaczenie terenu pod zieleń nie zostaną uwzględnione, miasto powinno przynajmniej zwiększyć strefy ochrony zieleni osiedlowej.;Jeśli już powstanie tu osiedle, nie powinno być kolejną betonową pustynią. Uważam, że strefy ochrony zieleni osiedlowej powinny być większe.;Jeśli ostatecznie, wbrew uwagom mieszkańców, teren MW.14 zostanie przeznaczony pod zabudowę wielorodzinną, to tym bardziej należy rozszerzyć strefy ochrony zieleni osiedlowej.}
            '''
        },
        "green_mw15":
        {
            "title": "Uwagi dotyczące  MW.15",
            "content": '''{Strefy ochrony zieleni osiedlowej są nadal zbyt małe.;Choć wyznaczono kilka nowych stref ochrony zieleni osiedlowej, są one bardzo małe.;Niestety wyznaczone w nowym projekcie strefy zieleni osiedlowej są bardzo małe.}    
            {Wnioskuję, aby obszar MW.15 przeznaczyć pod zieleń urządzoną. Ale jeśli ten postulat nie zostanie wysłuchany, wnioskuję o istotne zwiększenie stref ochrony zieleni osiedlowej.;Strefy zieleni osiedlowej powinny być większe.;Jeśli miasto nie wysłucha uwag mieszkańców i przeznaczy teren MW.15 pod inwestycje, tym bardziej powinno się zwiększyć zaplanowane na nim strefy ochrony zieleni osiedlowej.}
            '''
        },
        "green_mwu6":
        {
            "title": "Dotyczy MW.U/6",
            "content": '''{Teren zielony ZPz.6 obejmuje zaledwie połowę zieleni, która już istnieje w okolicy i powinna być zachowana.;Teren ZPz.6 jest szerszy, niż przewidziana wcześniej strefa zieleni, ale to nadal nie jest wystarczające, skoro przewidziano likwidację połowy okolicznej zieleni.;Obszar będący pierwotnie zielenią izolacyjną ZI.1 (teraz ZPz.6) został trochę poszerzony, ale trudno uznać to za akceptowalną odpowiedź na wcześniejsze uwagi mieszkańców.;Teren ZPz.6 (dawniej ZI.1) poszerzono tylko minimalnie. Nie zgadzam się z tym i zależy mi na utrzymaniu całej zieleni istniejącej w okolicy.;Niewielkie rozszerzenie terenu pierwotnie wskazanego jako ZI.1 (obecnie ZPz.6) jest niewystarczające.;Teren ZPz.6 to w większości teren opisany w pierwszym projekcie jako ZI.1. Poszerzono go tylko minimalnie, mimo że mieszkańcy już wcześniej oczekiwali zachowania już istniejącej tu zieleni.}
            {Tak niewielka zmiana w stosunku do pierwszego projektu nie odpowiada na wcześniejsze uwagi. Miasto w odpowiedzi na nie deklarowało ich częściowe uwzględnienie, ale trudno uznać za akceptowalną zmianę, która jest tak kosmetyczna.;Uważam, że tak niewielkie uwzględnienie uwag mieszkańców do pierwotnego projektu w ogóle nie jest satysfakcjonujące.;Miasto uwzględniło w tym zakresie w części uwagi mieszkańców. Dlatego powinno wprowadzić realne, a nie minimalne zmiany.}    
            {Proszę włączyć cały teren oznaczony jako MW/U.6 do ZPz.6, aby zachować tu istniejącą zieleń. Mieszkańcom zależy na jej utrzymaniu.; Uważam, że mieszkańcy ulic Pszczelnej i Bułgarskiej nie powinni stracić dostępu do zieleni. Zielenią urządzoną powinien być cały teren MW/U.6.;Opierając się na prognozie oddziaływania na środowisko proszę o przeznaczenie terenu MW/U.6 pod zieleń urządzoną i połączenie go z ZPz.6.}
            '''
        }
    }

TITLE_TXT = "Uwagi do projektu miejscowego planu zagospodarowania przestrzennego obszaru \"Kobierzyńska\""
INTRO_TXT = "Odpowiadając na ogłoszenie Prezydenta Miasta Krakowa z 2 października 2020 r. składam następujące uwagi:"

