TXT = {"green_general":
        {
            "title": "Dotyczy MW.11, MW.12, MW.14, MW.15 i MW.16",
            "content": '''{Choć wyłożenie dotyczy tylko niewielkich zmian w stosunku do pierwszego projektu, należy przypomnieć, że według uwag setek mieszkańców południowa część obszaru nie powinna być obszarem inwestycyjnym.;Nieliczne poprawki w stosunku do pierwotnego projektu MPZP nie zmieniają jego ogólnego obrazu - wbrew bardzo licznym uwagom mieszkańców przeznaczono niezabudowany jeszcze obszar w ogromnej większości pod zabudowę wielorodzinną.;Zmiany objęte ponownym wyłożeniem nie są wystarczające i nie odpowiadają na liczne wcześniejsze uwagi mieszkańców.;Plan poddany ponownemu wyłożeniu nie odpowiada wystarczająco na liczne wcześniejsze uwagi.;Projektowany plan, mimo niewielkich zmian, nadal niesłusznie przeznacza niemal cały niezabudowany dotąd teren pod inwestycje.;Modyfikacje wprowadzone w kolejnej wersji projektu są niewielkie i nadal większość terenu objętego planem ma być poddana intensywnej zabudowie.;Zmiany w stosunku do pierwotnej wersji nie są adekwatną reakcją na zastrzeżenia zgłaszane przez mieszkańców, którzy opierali się na dokumentach analitycznych sporządzonych w Urzędzie Miasta (zwłaszcza prognozie oddziaływania na środowisko).} 
            {Niestety także ponownie wyłożony projekt zakłada, że obszary cenne  przyrodniczo i spełniające ważne funkcje retencyjne zostaną niemal w całości zabudownae.;Także ponownie wyłożony projekt przewiduje zabdowę obszarów, które zarówno w świetle dokumentów sporządzanych w Urzędzie, jak i w rzeczywistości są cenne przyrodniczo.;Zaktualizowany projekt wciąż zakłada objęcie inwestycjami obszarów cennych przyrodniczo.;Jak wynika z poddanej aktualizacji prognozy oddziaływania na środowisko, realizacja ustaleń planu negatywnie wpłynie na istniejące cenne siedliska, a także na retencyjne funkcje terenu.;Twórcy prognozy oddziaływania na środowisko ostrzegają, że zabudowa terenu negatywnie wpłynie na tereny otaczające obszar opracowania, w szczególności obszar Lasu Borkowskiego.;Jak wynika nawet z poddanej aktualizacji prognozy oddziaływania na środowisko, przeznaczenie niezabudowanej części terenu pod inwestycje wpłynie niekorzytnie na przyrodę oraz zakłóci stosunki wodne, grożąc częstszymi podtopieniami.} 
            {Należy przeznaczyć tereny MW.11, MW.12, MW.14, MW.15 i MW.16 pod zieleń urządzoną.;Miasto powinno przeznaczyć tereny w południowej części obszaru pod zieleń urządzoną (np. park).;Wciąż aktualne są uwagi, zgodnie z którymi tereny MW.11, MW.12, MW.14 i MW.16 powinny w całości zostać przeznaczone na zieleń urządzoną (ZP, np. park).;Zdecydowanie uważam, że tereny w południowej części obszaru powinny być przeznaczone pod zieleń, a nie pod kolejne osiedla.;Dlatego tereny MW.11, MW.12, MW.14 i MW.16 powinny w całości zostać przeznaczone na zieleń urządzoną (ZP), co otworzyłoby to drogę do wykupu tych terenów przez miasto.;Obowiązujące studium uwarunkowań dopuszcza przeznacenie pod zieleń urządzoną terenów oznaczonych ogólnie jako MW. Tak należy uczynić w przypadku obszarów MW.11, MW.12, MW.14, MW.15 i MW.16.;Tereny MW.11, MW.12, MW.14, MW.15 i MW.16 należy przeznaczyć pod zieleń urządzoną.;Tereny MW.11, MW.12, MW.14, MW.15 i MW.16 nie powinny być obszarami inwestycyjnymi - mamy ich już dość w okolicy. Powinny pozostać zielone, a by miasto mogło je wykupić z rąk prywatnych, powinny być przeznaczone w planie pod zieleń urządzoną.}'''
        },
        "green_roofs":
        {
            "title": "Dotyczy MW.8, MW.11, MW.12, MW/U.6",
            "content": '''{Jeżeli ostatecznie, wbrew uwagom mieszkańców, tereny te zostaną terenami inwestycyjnymi, to należy rozszerzyć obowiązek stosowania dachu zielonego intensywnego;Intensywne dachy zielone powinny być stosowane obowiązkowo także na budynkach mieszkalnych, tak jak na terenach MW.14, MW.15 i MW.16.;Obowiązek umieszczania dachów zielonych intensywnych powinien dotyczyć wszystkich terenów, co do których miasto upiera się, aby przeznaczyć je pod budownictwo mieszkalne.;Ograniczanie wymogu stosowania intnsywnych dachów zielonych tylko do garaży podziemnych nie ma uzasadnionego powodu.} 
            {Stosowanie wszędzie takich dachów rekompensowałby choć w części oddanie terenu pod inwestycje i związane z tym straty.;Powinno się w jak największym stopniu zabezpieczyć możliwość retencjonowania wody - najlepiej zadziałałoby tu przeznaczenie terenu pod zieleń, ale jeśli miasto nie wysłucha tu mieszkańców, powinno i tak dążyć do zachowania retencji.;Skoro dachy zielone intensywne mają być stosowane na budynkach mieszkalnych na obszarach oznaczonych jako MW.14-MW.16, to ten sam wymóg powinien być stosowany także na innych terenach inwestycyjnych.;Zastosowanie intensywnych dachów zielonych, choć nie zastąpi terenów zielonych, przynajmniej w części będzie dawać korzyści związane z retencjonowaniem opadów.} 
            {Zielone intensywne dachy należy stosować na budynkach mieszkalnych na wszystkich obszarach przeznaczanych pod zabudowę wielorodzinną.;Dachy zielone intensywne powinny być stosowane na budynkach mieszkalnych także na obszarach MW.8, MW.11, MW.12, MW/U.6.;Na obszarach MW.8, MW.11, MW.12, MW/U.6 dachy zielone intensywne należy stosować nie tylko na garażach, ale także na budynkach.;Obowiązek stosowania zielonych dachów intensywnych na budynkach mieszkalnych powinien dotyczyć także MW.8, MW.11, MW.12, MW/U.6.}
            '''
        },
        "green_mw11":
        {
            "title": "Dotyczy MW.11",
            "content": '''{Wprowadzony w nowej wersji projektu pas zieleni między MW.11 a już zabudowanym terenem MW.9 nie jest wystarczająco szeroki i mimo jej wprowadzenia teren inwestycyjny przedziela dwa cenne przyrodniczo tereny zielone (tj. ZPw.4 i ZPz.4).;Nowa strefa zieleni osiedlowej w części MW.11 graniczącej z MW.9 jest zdecydowanie zbyt mała.;Strefa zieleni osiedlowej między MW.11 a MW.9 jest zdecydowanie zbyt mała.;Strefa zieleni osiedlowej w zachodniej części obszaru MW.11 jest zbyt mała - nadal teren inwestycyjny oddziela dwa cenne tereny zielone, które w planie przewidziano do utrzymania (tj. ZPw.4 i ZPz.4).}            
            {Jeżeli wbrew wielu dotychczasowym uwagom mieszkańców teren MW.11 zostanie terenem inwestycyjnym, dodany w nowym projekcie pas zieleni powinen być znacznie poszerzony, tak by sięgał od granicy z MW.9 aż do terenu ZPz.4.;Należy w jak największym stopniu utrzymać przyrodnicze i retencyjne walory terenu obecnie oznaczonego jako MW.11. Jeśli wbrew zastrzeżeniom mieszkańców teren zostanie przeznaczony pod zabudowę wielorodzinną, tereny ZPz.4, ZPw.4, nowy pas zieleni osiedlowej i obszar znajdujący się pomiędzy nimi powinny zostać połączone, a w ten sposób powinno się utworzyć jedną przestrzeń przeznaczoną pod zieleń urządzoną (np. park).;Przynajmniej obszar między terenem ZPz.4 a terenem ZPw.4 i MW.9 należy przeznaczyć pod zieleń urządzoną.} 
            {Ponadto, należy zabronić na obszarze MW.11 budowy garaży podziemnych, które spowodowałyby utratę jego walorów retencyjnych.;Niezależnie od tego, aby zachować retencyjność terenu, należy zakazać zabudowy głębokiej (garaży podziemnych).;Ponadto, należy zmniejszyć intensywność zabudowy przez zwiększenie minimalnego wskaźnika terenu biologicznie czynnego do 60%, ustalenie maksymalnego wskaźnika powierzchni zabudowy na 25% i wskaźnika intensywności zabudowy na 0,1-1,0.;Niezależnie od powyższego, jeśli obszar MW.11 miałby zostać przeznaczony pod zabudowę, maksymalną wysokość zabudowy należy zmniejszyć do 11 metrów (trzech kondygnacji). Należy też ograniczyć długość elewacji, podobnie jak dla MW.12. Pozwoli to zachować spójność z sąsiadującą zabudową jednorodzinną.}

            '''
        },
        "green_mw12":
        {
            "title": "Dotyczy MW.12",
            "content": '''{Jeśli miasto zamierza zignorować głos mieszkańców i przeznaczyć teren pod zabudowę, powinno i tak dążyć do zmniejszenia presji na środowisko i w jak największym stopniu z zachować harmonijne sąsiedztwo z okolicznymi terenami objętymi zabudową jednorodzinną.;Jeśli teren miałby, wbrew licznym uwagom mieszkańców, zostać przeznaczony pod inwestycje, utratę jego zdolności do retencji należy utrzymać na jak najmniejszym poziomie. Konieczne jest też zachowanie harmonii z sąsadującymi budynkami jednorodzinnymi.;Zakładając, że wbrew uwagom mieszkańców opartym na prognozie oddziaływania na środowisko, teren MW.12 ma stać się terenem inwestycyjnym, powinno się zmniejszyć wysokość zabudowy i zachować jak najwięcej zdolności tego terenu do retencji wody.} 
            {Z tego powodu należy zabronić na obszarze MW.12 budowy garaży podziemnych, które spowodowałyby utratę jego walorów retencyjnych, a także zmniejszyć maksymalną wysokość zabudowy.;Dlatego wykluczone powinno być stosowanie tzw. zabudowy głębokiej, a zwłaszcza garaży podziemnych. Należy też dostosować (zmniejszyć) wysokość budynków mieszkalnych, adekwatnie do wysokości sąsiadujących domów jednorodzinnych.;Dlatego należy zmniejszyć intensywność zabudowy przez zwiększenie minimalnego wskaźnika terenu biologicznie czynnego do 60%, ustalenie maksymalnego wskaźnika powierzchni zabudowy na 25% i wskaźnika intensywności zabudowy na 0,1-1,0.;Powinno się ograniczyć wysokość zabudowy do 11 metrów (3 kondygnacje), aby nowe wielorodzinne osiedle nie odstawało od sąsiednich domów jednorodzinych. Z kolei aby ograniczyć ryzyko utraty walorów retencyjnych i związanych z tym podtopień, powinno się  wykluczyć zabudowę głęboką (garaże podziemne).}

            '''
        },
        "green_mw14":
        {
            "title": "Dotyczy MW.14",
            "content": '''{Obszary zieleni urządzonej sąsiadujące z MW.14 i strefy zieleni siedlowej są zdecydowanie niewystarczające.;Poszerzenie terenu ZPw.5 jest minimalne, a wskutek jednoczesnego zmniejszenia terenu ZPw.7 łączna powierzchnia zieleni w okolicy terenu MW.14 pozostała bardzo mała.}            
            {Teren MW.14, w ślad za wcześniejszymi uwagami mieszkańców i zgodnie z dokumentami dotyczącymi jego stanu przyrodniczego, powinien być parkiem. Jeśli miasto nie chce tego postulatu wysłuchać, powinno przynajmniej znacząco poszerzyć strefy zieleni osiedlowej.;Jeżeli teren MW.14 zostanie ostatecznie przeznaczony pod zabudowę wielorodzinną, należy istotnie rozszerzyć wyznaczone na nim strefy ochrony zieleni osiedlowej.;Jeśli w ostatecznym projekcie uwagi mieszkańców sprzeciwiających się przeznaczeniu obszaru MW.14 pod inwestycje nie zostaną uwzględnione, to przynajmniej należy zwiększyć strefy ochrony zieleni osiedlowej.;Należy realnie zwiększyć powierzchnię zieleni na terenie MW.14, przynajmniej poszerzając wyznaczone na nim strefy ochrony zieleni osiedlowej.;Jeśli ostatecznie, wbrew uwagom mieszkańców, teren MW.14 zostanie przeznaczony pod zabudowę wielorodzinną, to tym bardziej należy rozszerzyć strefy ochrony zieleni osiedlowej.}
            '''
        },
        "green_mw15":
        {
            "title": "Dotyczy MW.15",
            "content": '''{Strefy ochrony zieleni osiedlowej są nadal zbyt małe.;Nowe strefy ochrony zieleni osiedlowej nie mogą być uznane za wystarczające.;Nowe strefy przeznaczone pod zieleń osiedlową są nadal bardzo małe.}    
            {Uważam, że obszar MW.15 powinien być przeznaczony pod zieleń urządzoną. Jeśli jednak miasto zamierza tego postulatu nie wysłuchać, postuluję znaczne zwiększenie stref ochrony zieleni osiedlowej.;Powinno się przynajmniej znacząco zwiększyć strefy zieleni osiedlowej, aby obejmowały wszystkie najcenniejsze przyrodniczo fragmenty MW.15.;Należy zwiększyć strefy zieleni osiedlowej tak, aby ich znacznie nie było wyłącznie "kosmetyczne".;Jeśli ostatecznie, wbrew uwagom mieszkańców, teren MW.15 zostanie przeznaczony pod zabudowę wielorodzinną, to tym bardziej należy rozszerzyć strefy ochrony zieleni osiedlowej.}
            '''
        },
        "green_mwu6":
        {
            "title": "Dotyczy MW.U/6",
            "content": '''{Wprowadzone w nowym projekcie niewielkie poszerzenie terenu zielonego (ZPz.6) jest stanowczo niewystarczające.;Mimo że obszar będący pierwotnie zielenią izolacyjną ZI.1 (teraz ZPz.6) został trochę zwiększony, jest to niewystarczające.;Teren ZPz.6 (dawniej ZI.1) poszerzono tylko minimalnie.;Niewielkie rozszerzenie terenu pierwotnie wskazanego jako ZI.1 (obecnie ZPz.6) jest niewystarczające.;Teren ZPz.6 to tylko minimalnie zwiększony teren opisany pierwotnie jako ZI.1, co do którego zbyt małych rozmiarów mieszkańcy wypowiadali się już we wcześniejszych konsultacjach.}
            {Władze miasta w odpowiedzi na uwagi twierdziły, że je częściowo uwzględniły, jednak minimalne poszerzenie zieleni o wąski pasek to tylko kosmetyczna zmiana.;Minmalne poszerzenie nie jest dobrą odpowiedzią na wcześniejsze uwagi mieszkańców. Skoro miasto deklarowało uwzględnienie uwag, powinno potraktować poważnie własną deklarację.;Nie można uznać, że częściowe uwzględnienie uwag mieszkańców do pierwotnego projektu przełożyło się na choć trochę satysfakcjonujące zmiany.;Skoro miasto uwzględniło w tym zakresie w części uwagi mieszkańców (a tak wynikało z opublikowanej tabeli z ich rozpatrzeniem), powinno to zrobić poważnie, a nie kosmetycznie.}    
            {Wnioskuję, aby cały teren oznaczony jako MW/U.6 został włączony do ZPz.6 jako zieleń urządzona.; Mieszkańcy ulic Pszczelnej i Bułgarskiej powinni dysponować lepszym dostępem do zieleni i lepszą ochroną przed hałasem z Trasy Łagiewnickiej i projektowanej ul. 8 Pułku Ułanów. Dlatego zielenią urządzoną powinien być cały obszar MW/U.6.;Zgodnie z prognozą oddziaływania na środowisko wnioskuję, aby przeznaczyć cały teren MW/U.6 pod zieleń urządzoną i włączyć go do obszaru ZPz.6.}
            '''
        }
    }

TITLE_TXT = "Uwagi do projektu miejscowego planu zagospodarowania przestrzennego obszaru \"Kobierzyńska\""
INTRO_TXT = "W odpowiedzi na ogłoszenie Prezydenta Miasta Krakowa z 2 października 2020 r. składam następujące uwagi:"

